=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/schemas/schema-3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <!-- Enumaration of possible names for TrasportType-->
    <xs:simpleType name="transportName">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Metro"/>
            <xs:enumeration value="Bus"/>
            <xs:enumeration value="Tram"/>
            <xs:enumeration value="Ferry"/>
            <xs:enumeration value="Train"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- TransportType definition-->
    <xs:complexType name="TransportType">
        <xs:sequence>
            <xs:element name="name" type="transportName"/>
        </xs:sequence>
    </xs:complexType>
     <!--ListOfTimes definition-->
     <xs:simpleType name="ListOfTimes">
        <xs:list itemType="xs:time"/>
    </xs:simpleType>
    <!--ListOfTimes definition-->
    <xs:simpleType name="ListOfDates">
        <xs:list itemType="xs:date"/>
    </xs:simpleType>
    <!--Departures definition-->
    <xs:complexType name="Departures">
        <xs:sequence>
            <xs:element name="businessDay" type="ListOfTimes" minOccurs="1" maxOccurs="1"/>
            <xs:element name="saturday" type="ListOfTimes" minOccurs="1" maxOccurs="1"/>
            <xs:element name="sunday" type="ListOfTimes" minOccurs="1" maxOccurs="1"/>
            <xs:element name="holidays" type="ListOfDates" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <!--TrafficLineStation definition-->
    <xs:complexType name="TrafficLineStation">
        <xs:sequence>
            <xs:element name="order" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="minutesToNext" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="hasStationId" type="xs:integer" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <!--TrafficLineStations definition-->
    <xs:complexType name="TrafficLineStations">
        <xs:sequence>
            <xs:element name="TrafficLineStation" type="TrafficLineStation" minOccurs="2" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <!--TrafficLine definition-->
    <xs:complexType name="TrafficLine">
        <xs:sequence>
            <xs:element name="trafficLineId" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="transportType" type="TransportType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="contains" type="TrafficLineStations" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Departures" type="Departures" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <!--ROOT-->
    <xs:element name="TrafficLines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TrafficLine" type="TrafficLine" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/data/data-3.xml
<?xml version="1.0" encoding="utf-8"?>
<TrafficLines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/schema-3.xsd">
    <TrafficLine>
        <trafficLineId>22</trafficLineId>
        <transportType>
            <name>Tram</name>
        </transportType>
        <contains>
            <TrafficLineStation>
                <order>1</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>1</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>2</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>2</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>3</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>3</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>4</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>4</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>5</order>
                <minutesToNext>5</minutesToNext>
                <hasStationId>5</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>6</order>
                <minutesToNext>7</minutesToNext>
                <hasStationId>6</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>7</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>7</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>8</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>8</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>9</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>9</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>10</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>10</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>11</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>11</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>12</order>
                <minutesToNext>4</minutesToNext>
                <hasStationId>12</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>13</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>13</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>14</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>14</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>15</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>15</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>16</order>
                <minutesToNext>5</minutesToNext>
                <hasStationId>16</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>17</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>17</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>18</order>
                <minutesToNext>4</minutesToNext>
                <hasStationId>18</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>19</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>19</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>20</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>20</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>21</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>21</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>22</order>
                <minutesToNext>4</minutesToNext>
                <hasStationId>22</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>23</order>
                <minutesToNext>5</minutesToNext>
                <hasStationId>23</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>24</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>24</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>25</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>25</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>26</order>
                <minutesToNext>0</minutesToNext>
                <hasStationId>26</hasStationId>
            </TrafficLineStation>
        </contains>
        <Departures>
            <businessDay>
                05:30:00 06:30:00 07:30:00 08:30:00 09:30:00 10:30:00 11:30:00 12:30:00 13:30:00 14:30:00 15:30:00 16:30:00 17:30:00 18:30:00 19:30:00 20:30:00 21:30:00 22:30:00 23:30:00
            </businessDay>
            <saturday>
                15:30:00 17:30:00 19:30:00 21:30:00
            </saturday>
            <sunday>
                15:30:00 18:30:00 21:30:00
            </sunday>
            <holidays>
                2023-01-01 2023-05-01 2023-05-08 2023-07-05 2023-07-06 2023-09-28 2023-10-28 2023-11-17 2023-12-24 2023-12-25 2023-12-26
            </holidays>
        </Departures>
    </TrafficLine>
    <TrafficLine>
        <trafficLineId>15</trafficLineId>
        <transportType>
            <name>Tram</name>
        </transportType>
        <contains>
            <TrafficLineStation>
                <order>1</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>27</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>2</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>28</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>3</order>
                <minutesToNext>4</minutesToNext>
                <hasStationId>28</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>4</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>29</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>5</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>9</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>6</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>10</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>7</order>
                <minutesToNext>2</minutesToNext>
                <hasStationId>11</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>8</order>
                <minutesToNext>4</minutesToNext>
                <hasStationId>12</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>9</order>
                <minutesToNext>0</minutesToNext>
                <hasStationId>30</hasStationId>
            </TrafficLineStation>
        </contains>
        <Departures>
            <businessDay>
                07:30:00 08:30:00 09:30:00 10:30:00 11:30:00 12:30:00 13:30:00 14:30:00 15:30:00 16:30:00 17:30:00 18:30:00 19:30:00 20:30:00 21:30:00 22:30:00 23:30:00
            </businessDay>
            <saturday>
                09:30:00 11:30:00 13:30:00 15:30:00
            </saturday>
            <sunday>
                09:00:00 10:00:00 11:00:00
            </sunday>
            <holidays>
                2023-01-01 2023-05-08 2023-09-28 2023-10-28 2023-11-17 2023-12-24 2023-12-25 2023-12-26
            </holidays>
        </Departures>
    </TrafficLine>
    <TrafficLine>
        <trafficLineId>283</trafficLineId>
        <transportType>
            <name>Train</name>
        </transportType>
        <Departures>
            <businessDay>
                10:30:00 11:00:00 11:30:00 12:00:00 12:30:00
            </businessDay>
            <saturday>
                12:30:00
            </saturday>
            <sunday>
                16:30:00
            </sunday>
            <holidays>
                2023-01-01 2023-09-28 2023-10-28 2023-12-24 2023-12-25 2023-12-26
            </holidays>
        </Departures>
    </TrafficLine>
    <TrafficLine>
        <trafficLineId>80</trafficLineId>
        <transportType>
            <name>Funicular</name>
        </transportType>
        <contains>
            <TrafficLineStation>
                <order>1</order>
                <minutesToNext>1</minutesToNext>
                <hasStationId>80</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>2</order>
                <minutesToNext>3</minutesToNext>
                <hasStationId>81</hasStationId>
            </TrafficLineStation>
            <TrafficLineStation>
                <order>3</order>
                <minutesToNext>0</minutesToNext>
