=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <!--Ticket definition-->
    <xs:complexType name="Ticket">
        <xs:sequence>
            <xs:element name="ticketId" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="validFrom" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
            <xs:element name="validTo" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <!--DestinationTicket definition-->
    <xs:complexType name="TimeTicket">
        <xs:complexContent>
            <xs:extension base="Ticket" />
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DestinationTicket">
        <xs:complexContent>
            <xs:extension base="Ticket">
                <xs:sequence>
                    <xs:element name="fromStationId" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="toStationId" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <!-- List of tckets that passenger owns-->
    <xs:complexType name="TimeTickets">
        <xs:sequence>
            <xs:element name="TimeTicket" type="TimeTicket" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DestinationTickets">
        <xs:sequence>
            <xs:element name="DestinationTicket" type="DestinationTicket" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <!--Passenger definition-->
    <xs:complexType name="Passenger">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="owns" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="timeTickets" type="TimeTickets" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="destinationTickets" type="DestinationTickets" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute ref="xml:lang"/>
    </xs:complexType>
    <!-- ROOT-->
    <xs:element name="Passengers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Passenger" type="Passenger" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Passengers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/schema-1.xsd">
    <Passenger xml:lang="cs">
        <firstName>Milan</firstName>
        <surname>Hrušovský</surname>
        <owns>
            <destinationTickets>
                <DestinationTicket>
                    <ticketId>1</ticketId>
                    <validFrom>2023-04-17T17:00:00</validFrom>
                    <validTo>2023-04-17T23:59:59</validTo>
                    <fromStationId>100</fromStationId>
                    <toStationId>103</toStationId>
                </DestinationTicket>
            </destinationTickets>
        </owns>
    </Passenger>
    <Passenger xml:lang="en">
        <firstName>Frodo</firstName>
        <surname>Bublik</surname>
        <owns>
            <timeTickets>
                <TimeTicket>
                    <ticketId>2</ticketId>
                    <validFrom>2023-01-25T17:00:00</validFrom>
                    <validTo>2023-01-25T20:00:00</validTo>
                </TimeTicket>
            </timeTickets>
        </owns>
    </Passenger>
    <Passenger xml:lang="en">
        <firstName>Darth</firstName>
        <surname>Vader</surname>
        <owns>
            <timeTickets>
                <TimeTicket>
                    <ticketId>3</ticketId>
                    <validFrom>2022-12-04T23:30:00</validFrom>
                    <validTo>2022-12-05T00:30:00</validTo>
                </TimeTicket>
            </timeTickets>
            <destinationTickets>
                <DestinationTicket>
                    <ticketId>5</ticketId>
                    <validFrom>2023-04-20T09:00:00</validFrom>
                    <validTo>2023-04-20T20:00:00</validTo>
                    <fromStationId>100</fromStationId>
                    <toStationId>103</toStationId>
                </DestinationTicket>
            </destinationTickets>
        </owns>
    </Passenger>
    <Passenger xml:lang="en">
        <firstName>Luke</firstName>
        <surname>Skywalker</surname>
        <owns>
            <timeTickets>
                <TimeTicket>
                    <ticketId>4</ticketId>
                    <validFrom>2022-12-24T17:00:00</validFrom>
                    <validTo>2022-12-24T18:00:00</validTo>
                </TimeTicket>
            </timeTickets>
            <destinationTickets>
                <DestinationTicket>
                    <ticketId>6</ticketId>
                    <validFrom>2023-04-17T12:00:00</validFrom>
                    <validTo>2023-04-17T22:00:00</validTo>
                    <fromStationId>104</fromStationId>
                    <toStationId>103</toStationId>
                </DestinationTicket>
            </destinationTickets>
        </owns>
    </Passenger>
</Passengers>
