=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/schemas/schema-2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
     <!-- Enumaration of possible names for TrasportType-->
     <xs:simpleType name="transportName">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Metro"/>
            <xs:enumeration value="Bus"/>
            <xs:enumeration value="Tram"/>
            <xs:enumeration value="Ferry"/>
            <xs:enumeration value="Train"/>
            <xs:enumeration value="Funicular"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- TransportType definition-->
    <xs:complexType name="TransportType">
        <xs:sequence>
            <xs:element name="name" type="transportName"/>
        </xs:sequence>
        <xs:attribute ref="xml:lang"/>
    </xs:complexType>
    <!-- Station definition-->
    <xs:complexType name="Station">
        <xs:sequence>
            <xs:element name="stationId" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="latitude" type="xs:float" minOccurs="1" maxOccurs="1"/>
            <xs:element name="longitude" type="xs:float" minOccurs="1" maxOccurs="1"/>
            <xs:element name="transportType" type="TransportType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="xml:lang"/>
    </xs:complexType>
    <!--ROOT-->
    <xs:element name="Stations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Station" type="Station" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== lhotanok/data-formats/NPRG036-T1G2-HW3/3/xml/data/data-2.xml
<?xml version="1.0" encoding="utf-8"?>
<Stations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/schema-2.xsd">
    <Station xml:lang="cs">
        <stationId>1</stationId>
        <name>Bílá Labuť</name>
        <latitude>50.090168</latitude>
        <longitude>14.43547</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>2</stationId>
        <name>Masarykovo Nádraží</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
        <transportType>
            <name>Bus</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>3</stationId>
        <name>Jindřišská</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>4</stationId>
        <name>Václavské náměstí</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>5</stationId>
        <name>Vodičkova</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>6</stationId>
        <name>Lazarská</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>7</stationId>
        <name>Národní Třída</name>
        <latitude>50.081158</latitude>
        <longitude>14.4195921</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>8</stationId>
        <name>Národní Divadlo</name>
        <latitude>50.0824531</latitude>
        <longitude>14.4131844</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>9</stationId>
        <name>Újezd</name>
        <latitude>50.081676</latitude>
        <longitude>14.404443</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>10</stationId>
        <name>Hellichova</name>
        <latitude>50.085659</latitude>
        <longitude>14.404176</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>11</stationId>
        <name>Malostranské Náměstí</name>
        <latitude>50.08798</latitude>
        <longitude>14.40433</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
        <transportType>
            <name>Bus</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>12</stationId>
        <name>Malostranská</name>
        <latitude>50.090363</latitude>
        <longitude>14.410101</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>13</stationId>
        <name>Královský Letohrádek</name>
        <latitude>50.094265</latitude>
        <longitude>14.404549</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>14</stationId>
        <name>Pražský Hrad</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>15</stationId>
        <name>Brusnice</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>16</stationId>
        <name>Pohořelec</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>17</stationId>
        <name>Malovanka</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
        <transportType>
            <name>Bus</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>18</stationId>
        <name>Marjánka</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
        <transportType>
            <name>Bus</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>19</stationId>
        <name>Drinopol</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>20</stationId>
        <name>U Kaštanu</name>
        <latitude>50.08363</latitude>
        <longitude>14.36335</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>21</stationId>
        <name>Břevnovský Klášter</name>
        <latitude>50.093323</latitude>
        <longitude>14.398007</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>22</stationId>
        <name>Říčanova</name>
        <latitude>50.08133</latitude>
        <longitude>14.35277</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>23</stationId>
        <name>Vypich</name>
        <latitude>50.0796863</latitude>
        <longitude>14.3464722</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
        <transportType>
            <name>Bus</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>24</stationId>
        <name>Obora Hvězda</name>
        <latitude>50.078121</latitude>
        <longitude>14.340657</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>

    <Station xml:lang="cs">
        <stationId>25</stationId>
        <name>Malý Břevnov</name>
        <latitude>50.076279</latitude>
        <longitude>14.332569</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>26</stationId>
        <name>Bílá Hora</name>
        <latitude>50.07555</latitude>
        <longitude>14.32279</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>27</stationId>
        <name>Anděl</name>
        <latitude>50.07193</latitude>
        <longitude>14.4036309</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>28</stationId>
        <name>Arbesovo náměstí</name>
        <latitude>50.0762107</latitude>
        <longitude>14.4041746</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>29</stationId>
        <name>Švandovo divadlo</name>
        <latitude>50.0762107</latitude>
        <longitude>14.4041746</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>30</stationId>
        <name>Čechův most</name>
        <latitude>50.0940657</latitude>
        <longitude>14.4167362</longitude>
        <transportType>
            <name>Tram</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>80</stationId>
        <name>Petřín</name>
        <latitude>50.0819497</latitude>
        <longitude>14.3966883</longitude>
        <transportType>
            <name>Funicular</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>81</stationId>
        <name>Nebozízek</name>
        <latitude>50.08226</latitude>
        <longitude>14.39926</longitude>
        <transportType>
            <name>Funicular</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>82</stationId>
        <name>Újezd</name>
        <latitude>50.082649</latitude>
        <longitude>14.403681</longitude>
        <transportType>
            <name>Funicular</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>100</stationId>
        <name>Praha hl.n.</name>
        <latitude>50.0832088</latitude>
        <longitude>14.4353059</longitude>
        <transportType>
            <name>Train</name>
        </transportType>
    </Station>
    <Station xml:lang="cs">
        <stationId>101</stationId>
        <name>Kolín</name>
        <latitude>50.0251424</latitude>
        <longitude>15.2135959</longitude>
        <transportType>
            <name>Train</name>
        </transportType>
    </Station>
